# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0002_auto_20180127_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='users',
        ),
    ]
