# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0003_auto_20180127_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
    ]
