# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0004_remove_book_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_reviewer.Book'),
            preserve_default=False,
        ),
    ]
