# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0005_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='belt_reviewer.User'),
            preserve_default=False,
        ),
    ]
